config/routes.rb
Ninetyninecats::Application.routes.draw do
  resources :cats

  resources :cat_rental_requests do
    member do
      put 'approve'
      put 'deny'
    end
  end

  resources :users
  resource :session

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id
  validates :age, numericality: true
  validates :age, :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: { in: ["red", "green", "blue"]}
  validates :sex, inclusion: { in: ["M", "F"]}

  has_many(
  :rental_requests,
  dependent: :destroy,
  class_name: "CatRentalRequest",
  foreign_key: :cat_id,
  primary_key: :id
  )

  belongs_to(
  :owner,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )


end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :start_date, :end_date, :status

  validates :cat_id, :start_date, :end_date, :status, presence: true

  validates :status,  inclusion: {in: ["PENDING", "APPROVED", "DENIED"] }

  #before_validation :status ||= "PENDING"

  validate :overlapping_approved_requests

  belongs_to(
  :cat,
  class_name: "Cat",
  foreign_key: :cat_id,
  primary_key: :id
  )

  def overlapping_requests
    requests = CatRentalRequest.find_all_by_cat_id(self.cat_id)
    requests.select! do |request|
      self.start_date.between?(request.start_date, request.end_date) ||
       self.end_date.between?(request.start_date, request.end_date) ||
       request.start_date.between?(self.start_date, self.end_date)
    end

    requests
  end

  def overlapping_approved_requests
    reqs = overlapping_requests
    overlapping_and_approved = reqs.select do |request|
      request.status == "APPROVED" && request.id != self.id
    end

    unless overlapping_and_approved.empty?
      errors[:overlap] << "this request overlaps with an approved request!"
    end
  end

  def overlapping_pending_requests
    reqs = overlapping_requests
    overlapping_and_pending = reqs.select do |request|
      request.status == "PENDING" && request.id != self.id
    end

    overlapping_and_pending
  end

  def pending?
    self.status == "PENDING"
  end

  def deny!
    self.update_attribute(:status, "DENIED")
    self.save!
  end

  def approve!
    # self.update_attribute(:status, 'APPROVED')
    overlapping_and_pending = overlapping_pending_requests
    overlapping_ids = overlapping_and_pending.map{|req| req.id}

    CatRentalRequest.transaction do
      overlapping_and_pending.each do |request|
        request.update_attribute(:status, "DENIED")
        request.save!
      end

      self.update_attribute(:status, "APPROVED")
      self.save!
    end

  end


end

app/models/session_holder.rb
class SessionHolder < ActiveRecord::Base
  attr_accessible :user_id, :session_token, :environment

  belongs_to(
  :user,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :user_name, :password, :session_token
   validates :user_name, uniqueness: true
   before_validation :set_session_token

   has_many(
   :cats,
   class_name: "Cat",
   foreign_key: :user_id,
   primary_key: :id
   )

   has_many(
   :sessions,
   class_name: "SessionHolder",
   foreign_key: :user_id,
   primary_key: :id
   )

   def set_session_token
     session_token = SecureRandom::urlsafe_base64(16)
     if self.session_token.nil?
       self.update_attribute(:session_token, session_token)
     end
     # self.session_token = do something if self.session_token.nil?
   end

   def reset_session_token!
     session_token = SecureRandom::urlsafe_base64(16)
     self.update_attribute(:session_token, session_token)
     self.save!
   end

   def password=(password)
     self.password_digest = BCrypt::Password.create(password)
   end

   def is_password?(password)
     BCrypt::Password.new(self.password_digest).is_password?(password)
   end

   def self.find_by_credentials(user_name, password)
     u = find_by_user_name(user_name)
     return false if u.nil?
     return u if u.is_password?(password)
     false
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery

end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  before_filter :authorize, only:[:approve, :deny]


  def authorize
    unless current_user.id == Cat.find_by_id(params[:id]).user_id
      flash[:error] = "You do not own this cat!"
      redirect_to cats_url
    end

  end


  def new
    #@cat_rental_request = CatRentalRequest.new
    render :new
  end

  def create
    cat = CatRentalRequest.new(params[:cat_rental_request])
    if cat.save
      redirect_to cats_url
    else
      render :json => cat.errors, :status => :unprocessable_entity
    end
  end

  def approve
    cat = CatRentalRequest.find(params[:id])
    cat.approve!
    redirect_to cats_url
  end

  def deny
    cat = CatRentalRequest.find(params[:id])
    cat.deny!
    redirect_to cats_url
  end


end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :authorize, :only => [:edit, :update]

  def authorize
    unless current_user.id == Cat.find_by_id(params[:id]).user_id
      flash[:error] = "You do not own this cat!"
      redirect_to cats_url
    end
  end

  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    cat = Cat.new(params[:cat])
    u = current_user
    cat.update_attribute(:user_id, u.id)
    if cat.save
      redirect_to cats_url
    else
      render :json => cat.errors, :status => :unprocessable_entity
    end
  end

  def edit
    @cat = Cat.find_by_id(params[:id])
    render :edit
  end

  def update
    cat = Cat.find_by_id(params[:id])

    cat.update_attributes(params[:cat])

    if cat.save
      redirect_to cats_url
    else
      render :json => cat.errors, :status => :unprocessable_entity
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(*params[:session].values)
    if !user
      flash[:error] = "Your credentials are invalid!"
      redirect_to new_session_url
    else
      session_h = SessionHolder.new(user_id: user.id, session_token: user.session_token, environment: request.env["HTTP_USER_AGENT"])

      #error code for user.nil?
      #user.reset_session_token!
      if session_h.save
        session[:session_token] = user.session_token
        redirect_to cats_url
      else
        #errors
      end
    end
  end

  def destroy #logging out
    u = self.current_user


    sess = SessionHolder.find_by_user_id_and_session_token(u.id, u.session_token)
    sess.destroy
    session[:session_token] = nil
    redirect_to cats_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    u =User.new(params[:user])
    if u.save
      #redirect_to session_url
      self.current_user=(u)
      redirect_to cats_url
    else
      render :json => u.errors, :status => :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<form action="/cat_rental_requests" method="POST">
  Cat:<select name="cat_rental_request[cat_id]">
    <%Cat.all.each do |cat|%>
    <%= "<option value=#{cat.id}>#{cat.name}</option>".html_safe %>
    <%end%>
  </select><br>
  Rental start date:<input type="date" name="cat_rental_request[start_date]"><br />
  Rental end date:<input type="date" name="cat_rental_request[end_date]"><br />


  <input type="submit" value="Rent a cat">

</form>

app/views/cats/_form.html.erb
    <form action="<% if @cat.persisted? %>
                  <%=   "/cats/#{@cat.id}" %>
                  <% else %>
                  <%= "/cats" %>
                  <% end%>" method="POST">



     <%= '<input type="hidden" name="_method" value="PUT">'.html_safe if @cat.persisted? %>
     <input type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">
      Cat's name:<input type="text" value="<%= @cat.name %>" name="cat[name]"><br />
      Cat's age:<input type="text" value="<%= @cat.age %>" name="cat[age]"><br />
      Cat's sex:
      Male<input type="radio" <%= "checked".html_safe  if @cat.sex == "M" %> name="cat[sex]" id="cat_sex_male" value="M">
     Female<input type="radio" <%= "checked".html_safe  if @cat.sex == "F" %> name="cat[sex]" id="cat_sex_female" value="F"><br />
      Cat's color:<select name="cat[color]" id="cat_coat_color">
        <option value="red" <%= "selected".html_safe if @cat.color == "red" %> >Red</option>
        <option value="green" <%= "selected".html_safe if @cat.color == "green" %> >Green</option>
        <option value="blue" <%= "selected".html_safe if @cat.color == "blue" %> >Blue</option>
        </select><br />
      Cat's birth date:<input type="date" value="<%= @cat.birth_date %>" name="cat[birth_date]"><br />

      <input type="submit" value="Modify cat">

    </form>

app/views/cats/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Create a Cat!! </title>
  </head>
  <body>
    <h1>Please modify <%= @cat.name %>'s attributes</h1>
    <br>
    <br>

    <%= render "form", :cat => @cat %>

  </body>
</html>

app/views/cats/index.html.erb
<h1>All Cats</h1>

<br>
<br>
<table border="1">
<tr>
    <th>Name</th>
    <th>Age</th>
    <th>Sex</th>
    <th>Color</th>
    <th>Birth Date</th>
</tr>

<% @cats.each do |cat| %>
  <tr><td><%= link_to"#{cat.name}","cats/#{cat.id}" %></td>
  <td><%= "#{cat.age}" %> </td>
  <td><%= "#{cat.sex}" %></td>
  <td><%= "#{cat.color}" %></td>
  <td><%= "#{cat.birth_date}" %></td></tr>
<% end %>

</table>

app/views/cats/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Create a Cat!! </title>
  </head>
  <body>
    <h1>Please specify your cat's attributes</h1>
    <br>
    <br>
    <%= render "form", :cat => @cat %>
  </body>
</html>

app/views/cats/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=@cat.name%> Cat!!</title>
  </head>
  <body>
    <h1><%= @cat.name %></h1>
    <br>
    <br>
    <table border="1">
    <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Sex</th>
        <th>Color</th>
        <th>Birth Date</th>
    </tr>

      <tr><td><%= @cat.name %></td>
      <td><%= @cat.age %> </td>
      <td><%= @cat.sex %></td>
      <td><%= @cat.color %></td>
      <td><%= @cat.birth_date %></td></tr>


    </table><br>


    <table border = "1">
    <tr>
      <th>Start Date</th>
      <th>End Date</th>
    </tr>

    <% @cat.rental_requests.sort{|a,b| a.start_date <=> b.start_date}.each do |rental_request| %>
    <tr><td>  <%= rental_request.start_date%></td>
    <td>  <%= rental_request.end_date%> </td>


    <% if @cat.user_id == current_user.id %>
    <td><%=button_to("Approve", "http://localhost:3000/cat_rental_requests/#{rental_request.id}/approve", method: :put) if rental_request.pending? %> </td>
        <td><%=button_to("Deny", "http://localhost:3000/cat_rental_requests/#{rental_request.id}/deny", method: :put) if rental_request.pending? %> </td>
    </tr>
    <% end %>
    <% end %>
  </table>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninetyninecats</title>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
  <% if current_user.nil? %>
    <%= link_to("Sign up", new_user_url) %>
    <br>
    <%= link_to("log in", new_session_url) %>
  <% else %>
    <%= "welcome to 99cats " +  current_user.user_name %>
    <%= button_to("log out", session_url, method: :delete)%>
  <% end %>


<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Please Create Account</h1>
  <form action="<%= users_url %>" method="POST">
    <input type="hidden"
             name="authenticity_token"
             value="<%= form_authenticity_token %>">
    Username: <input type="text" name="user[user_name]" ><br>
    Password:&nbsp; <input type="password" name="user[password]">
    <br>
    <input type="submit" value = "Sign up">
  </form>